all:
  children:
    routers:
      hosts:
        router:
          ansible_host: 52.53.145.219
      vars:
        ansible_network_os: ios
        ansible_connection: network_cli
        ansible_network_cli_ssh_type: libssh
        ansible_user: ansible
        ansible_password: Cisco123!
        ansible_libssh_hostkeys: ssh-rsa
        ansible_become: yes
        ansible_become_method: enable
        ansible_become_password: Cisco123!