name: Ansible

on:
  workflow_dispatch: 
    inputs:
      playbook:
        description: "Playbook to run (relative to ansible/playbooks/)"
        required: true
        default: "verify_connectivity.yml"
        type: choice
        options:
          - verify_connectivity.yml
          - install_observability.yml
          - router_config.yml
  pull_request:
    branches: [ main ]

permissions:
  contents: read
  pull-requests: write

env:
  KEY_PATH: /tmp/ec2-key.pem
#  SSM_KEY_PARAMETER: /capstone/dev/ssh-key

jobs:
  run-playbook:
    name: Run Playbook
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

#      - name: Fetch SSH key from SSM Parameter Store
#        run: |
#          aws ssm get-parameter \
#            --name "${{ env.SSM_KEY_PARAMETER }}" \
#            --with-decryption \
#            --query "Parameter.Value" \
#            --output text > ${{ env.KEY_PATH }}
#          chmod 400 ${{ env.KEY_PATH }}

      - name: configure ssh key and permissions
        env: 
          SSH_KEY: ${{ secrets.SSH_KEY }}
        run: |
          printf '%s\n' "${{ secrets.EC2_INSTANCES_PRIVATE_KEY }}" > ${{ env.KEY_PATH }}
          chmod 400 ${{ env.KEY_PATH }}
  
      - name: Install Ansible and AWS collection
        run: |
          pip install ansible boto3 botocore
          ansible-galaxy collection install amazon.aws community.docker

      - name: Dry-run diff 
        id : ansible
        if: github.event.inputs.playbook != 'router_config.yml'
        continue-on-error: true
        env:
          ANSIBLE_HOST_KEY_CHECKING: "False"
          ANSIBLE_CONFIG: ansible/ansible.cfg
        run : |
            OUTPUT=$(ansible-playbook --check --diff \
              -i ansible/inventory/aws_ec2.yml \
              -e "ansible_ssh_private_key_file=${{ env.KEY_PATH }}" \
              ansible/playbooks/${{ github.event.inputs.playbook }}) || true
              echo "ansible_output<<EOF" >> $GITHUB_OUTPUT
              echo "$OUTPUT" >> $GITHUB_OUTPUT
              echo "EOF" >> $GITHUB_OUTPUT
      
      - name: Post dry run to PR
        if: github.event_name == 'pull_request'
        uses: actions/github-script@v7
        with: 
          script: |
            const output = `${{ steps.ansible.outputs.ansible_output }}`;

            const { data: comments } = await github.rest.issues.listComments({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
            });

            await github.rest.issues.createComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: context.issue.number,
                body: output,
              });

      - name: Run verify playbook
        if: github.event.inputs.playbook  == 'verify_connectivity.yml'
        env:
          ANSIBLE_HOST_KEY_CHECKING: "False"
          ANSIBLE_CONFIG: ansible/ansible.cfg
        run: |
          ansible-playbook \
            -i ansible/inventory/aws_ec2.yml \
            -e "ansible_ssh_private_key_file=${{ env.KEY_PATH }}" \
            ansible/playbooks/${{ github.event.inputs.playbook }}

      - name: Run install observability playbook
        if: github.event.inputs.playbook  == 'install_observability.yml'
        env:
          ANSIBLE_HOST_KEY_CHECKING: "False"
          ANSIBLE_CONFIG: ansible/ansible.cfg
        run: |
          ansible-playbook \
          -i ansible/inventory/aws_ec2.yml \
          -e "ansible_ssh_private_key_file=${{ env.KEY_PATH }}" \
          -e "grafana_admin_password=${{ secrets.GRAFANA_ADMIN_PASSWORD }}" \
          ansible/playbooks/install_observability.yml

      - name: Setup Terraform
        if: github.event.inputs.playbook == 'router_config.yml'
        uses: hashicorp/setup-terraform@v3

      - name: Terraform init
        if: github.event.inputs.playbook == 'router_config.yml'
        working-directory: ./terraform   # adjust to wherever your .tf files live
        run: terraform init

      - name: Run router config playbook
        if: github.event.inputs.playbook == 'router_config.yml'
        env:
          ANSIBLE_HOST_KEY_CHECKING: "False"
          ANSIBLE_CONFIG: ansible/ansible.cfg
        run: |
          cat "${GITHUB_WORKSPACE}/ansible/group_vars/all/output.json"
          ansible-playbook \
            -i ansible/inventory/aws_ec2.yml \
            -e "ansible_ssh_private_key_file=${{ env.KEY_PATH }}" \
            ansible/playbooks/router_config.yml
        
      - name: Clean up key
        if: always()
        run: rm -f ssh-key.pem
